[package]
name = "timeless_rogue"
version = "0.1.0"
edition = "2021"
author = "Markus Dick"

[dependencies]
ron = "0.7"
serde = { version = "1", features = ["derive"] }
rand = "0.8.5"
colored = "2.0.0"